name: "📝 Issue Template"
description: "모든 유형에 사용할 수 있는 공통 이슈 템플릿"
title: ""
labels: []
assignees: []
body:
  - type: dropdown
    id: issue_type
    attributes:
      label: "📌 이슈 유형"
      description: "이 이슈가 어떤 유형인지 선택하세요."
      options:
        - "Feature"
        - "Bug"
        - "Style"
        - "Documentation"
        - "Build"
        - "Refactor/Chore"
      placeholder: "선택해주세요"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📄 설명"
      description: "이슈에 대한 설명을 작성해주세요."
      placeholder: "자세히 적을수록 좋습니다!"
    validations:
      required: true

  - type: checkboxes
    id: tasks
    attributes:
      label: "✅ 작업할 내용"
      description: "이슈 해결을 위한 작업 항목을 체크해주세요."
      options:
        - "작업1"
        - "작업2"
        - "작업3"
      placeholder: "최대한 세분화 해서 적어주세요!"
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: "🙋🏻 참고 자료"
      description: "관련 자료나 링크가 있다면 작성해주세요."
      placeholder: "문서, 링크, 이미지 등"
    validations:
      required: false
